# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('health-care-system-example', ['health-care-system'])
    obj.source = 'health-care-system-example.cc'

