# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('health-care-system', ['network', 'lr-wpan', 'mobility', 'spectrum'])
    module.source = [
        'model/health-care-header.cc',
        'model/gateway.cc',
        'model/laptop.cc',
        'model/laptop-gateway-connection.cc',
        'model/gateway-to-nanobot-header.cc',
        'model/nano-communication.cc',
        ]

    headers = bld(features='ns3header')

    headers.module = 'health-care-system'

    headers.source = [
        'model/health-care-header.h',
        'model/gateway.h',
        'model/laptop.h',
        'model/laptop-gateway-connection.h',
        'model/gateway-to-nanobot-header.h',
        'model/nano-communication.h',
        ]


    # bld.ns3_python_bindings()

